name: studentspace

services:
  php:
    build: .
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html/
    networks:
      - studentspace-network

  db:
    image: mariadb:10.6.7
    restart: always
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: studentspace
      MARIADB_USER: user
      MARIADB_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    # tmpfs:
    # - /var/lib/mysql
    networks:
      - studentspace-network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: user
    networks:
      - studentspace-network

networks:
  studentspace-network:
    driver: bridge